// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eebbwnfkitnmceeokdqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlYmJ3bmZraXRubWNlZW9rZHFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NDkyODUsImV4cCI6MjA3NDMyNTI4NX0.598ObUJzFAusMFKjjlAL2HvZA1KMIxqyk9HED2zHpCQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});